### ISSUE TITLE
能去掉黑框隐藏运行吗

### ISSUE THREAD

**Issue by xiaojj2021** [yinsel/BypassAV#4]
上次那个微信图标的使用这个工具可以隐藏
https://github.com/yj94/BinarySpy/issues/1
这次的这个改了没用
![image](https://github.com/user-attachments/assets/fcb272a7-9051-410c-8dca-f22be2eed9ef)
改成图形界面 直接不上线了，只能控制台界面黑框才能运行

**Comment by yinsel** [comment]
> 上次那个微信图标的使用这个工具可以隐藏 [yj94/BinarySpy#1](https://github.com/yj94/BinarySpy/issues/1) 这次的这个改了没用 ![image](https://private-user-images.githubusercontent.com/97785068/358598502-fcb272a7-9051-410c-8dca-f22be2eed9ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NDIxMDYsIm5iZiI6MTcyMzg0MTgwNiwicGF0aCI6Ii85Nzc4NTA2OC8zNTg1OTg1MDItZmNiMjcyYTctOTA1MS00MTBjLThkY2EtZjIyYmUyZWVkOWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDIwNTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYTQwZTY4ZWIxNjFlYTM3Y2VhOTk1ZWZmZWM2M2Y1NTkwOWY1MTgwZTlmOWI1YTBiMmM2ZDE3OTNhZDZjZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rgAkVs9k0lzJMQ9K9CIkqdpsst2vY-FlzIPPWDhT58A) 改成图形界面 直接不上线了，只能控制台界面黑框才能运行



> 上次那个微信图标的使用这个工具可以隐藏 [yj94/BinarySpy#1](https://github.com/yj94/BinarySpy/issues/1) 这次的这个改了没用 ![image](https://private-user-images.githubusercontent.com/97785068/358598502-fcb272a7-9051-410c-8dca-f22be2eed9ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NDM1MzUsIm5iZiI6MTcyMzg0MzIzNSwicGF0aCI6Ii85Nzc4NTA2OC8zNTg1OTg1MDItZmNiMjcyYTctOTA1MS00MTBjLThkY2EtZjIyYmUyZWVkOWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDIxMjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNDcyNmFkYWMxZjJhN2Q5MzcwNjBmZDNkNjhjZDUwZDRiN2E0NGVlY2MwM2ZiYWIxMDhiNTNmODIxNDJhYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z3Yj8ay23vFoMzFfQb2LfdRNPgSP02CwiDHp2MZtW1M) 改成图形界面 直接不上线了，只能控制台界面黑框才能运行

后渗透场景的工具免杀依赖于cmd窗口进行命令输出，因此不支持去除黑框
